# Generated by Django 4.2.4 on 2023-08-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.FileField(upload_to=''),
        ),
    ]
